export enum WidthSize {
	"w-1" = "w-1",
	"w-2" = "w-2",
	"w-3" = "w-3",
	"w-4" = "w-4",
	"w-5" = "w-5",
	"w-6" = "w-6",
	"w-7" = "w-7",
	"w-8" = "w-8",
	"w-9" = "w-9",
	"w-10" = "w-10",
	"w-11" = "w-11",
	"w-12" = "w-12",
	"w-13" = "w-13",
	"w-14" = "w-14",
	"w-15" = "w-15",
	"w-16" = "w-16",
	"w-tag" = "w-tag",
	"w-footer" = "w-footer",
	"w-custom" = "w-custom",
	"w-custom2" = "w-custom2",
	"w-auto" = "w-auto",
	"w-full" = "w-full",
	"w-screen" = "w-screen",
}

export enum HeightSize {
	"h-1" = "h-1",
	"h-2" = "h-2",
	"h-3" = "h-3",
	"h-4" = "h-4",
	"h-5" = "h-5",
	"h-6" = "h-6",
	"h-7" = "h-7",
	"h-8" = "h-8",
	"h-9" = "h-9",
	"h-10" = "h-10",
	"h-11" = "h-11",
	"h-12" = "h-12",
	"h-13" = "h-13",
	"h-14" = "h-14",
	"h-15" = "h-15",
	"h-16" = "h-16",
	"h-custom" = "h-custom",
	"h-custom2" = "h-custom2",
	"h-auto" = "h-auto",
	"h-full" = "h-full",
	"h-screen" = "h-screen",
}

export type HeightType = keyof typeof HeightSize;
export type WidthType = keyof typeof WidthSize;
